filebeat.inputs:
  # Jellyfin application logs
  - type: log
    enabled: true
    paths:
      - /opt/jellyfin/config/log/*.log
    fields:
      service: jellyfin
      environment: oracle-cloud
    fields_under_root: false
    multiline:
      pattern: '^\['
      negate: true
      match: after

  # System logs
  - type: log
    enabled: true
    paths:
      - /var/log/syslog
      - /var/log/messages
    fields:
      service: system
      environment: oracle-cloud

  # Docker container logs
  - type: container
    enabled: true
    paths:
      - "/var/lib/docker/containers/*/*.log"
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"

filebeat.modules:
  - module: system
    syslog:
      enabled: true
    auth:
      enabled: true

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

# Output to Logstash on ELK server (via Tailscale)
output.logstash:
  hosts: ["${ELK_TAILSCALE_IP}:5044"]
  ssl.enabled: false

# Monitoring
monitoring:
  enabled: true
  cluster_uuid: homelab-cluster

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0640
